//
// Reserved interface IDs are:
//
//   - 100: Notification
//
//

[id(1)]
interface runtime {
    [id(1), type(call)]
    exit(code: int32) -> ()
    [id(2), type(call)]
    printchar(ch: char) -> ()
}
