//
// Reserved interface IDs are:
//
//   - 100: Notification
//
//

[id(1)]
interface runtime {
    [id(1), type(call)]
    exit(code: int32) -> ()
    [id(2), type(call)]
    printchar(ch: char) -> ()
    [id(3), type(call)]
    print_str(str: string) -> ()
}

[id(2)]
interface process {
    [id(1), type(call)]
    create(name: string) -> (proc: handle, pager_ch: channel)
    [id(2), type(call)]
    destroy(proc: handle) -> ()
    [id(3), type(call)]
    add_vm_area(proc: handle, start: uintptr, size: size, flags: uint8) -> ()
    [id(4), type(call)]
    send_channel(proc: handle, ch: channel) -> ()
}

[id(3)]
interface thread {
    [id(1), type(call)]
    spawn(proc: handle, start: uintptr, stack: uintptr, buffer: uintptr,
          arg: uintptr) -> (thread: handle)

    [id(2), type(call)]
    destroy(thread: handle) -> ()
}

[id(4)]
interface timer {
    [id(1), type(call)]
    set(ch: channel, initial: int32, interval: int32) -> (timer: handle)
    [id(2), type(call)]
    clear(timer: handle) -> ()
}

[id(9)]
interface kernel {
}

[id(15)]
interface io {
    [id(1), type(call)]
    listen_irq(ch: channel, irq: uint8) -> ()
    [id(2), type(call)]
    read_ioport(addr: uint64, size: size) -> (data: uint64)
    [id(3), type(call)]
    write_ioport(addr: uint64, size: size, data: uint64) -> ()
}

[id(10)]
interface server {
    [id(1), type(call)]
    connect(interface: uint8) -> (ch: channel)
}

[id(11)]
interface memmgr {
    [id(1), type(call)]
    alloc_pages(num_pages: size) -> (page: page)
}

[id(12)]
interface pager {
    [id(1), type(call)]
    fill(proc: handle, addr: uintptr, size: size) -> (page: page)
}

[id(30)]
interface storage_device {
    [id(1), type(call)]
    read(sector: uintptr, num_sectors: size) -> (page: page)
}
