oneway notifications(data: notifications);
oneway exception(task: task, exception: exception_type);
rpc page_fault(task: task, vaddr: vaddr, ip: vaddr, fault: pagefault)
        -> (paddr: paddr, attrs: pageattrs);
