/// The kernel sends this message to a pager task when an exception occurs.
oneway exception(task: task, exception: exception_type);

/// The kernel calls this RPC when a page fault occurs.
/// When the pager task replies, the kernel continues executing the page-faulted task.
rpc page_fault(task: task, uaddr: uaddr, ip: uaddr, fault: uint) -> ();
