// FIXME: remove
rpc add(x: int, y: int) -> (value: int);
rpc add2(x: bytes[7], Y: int) -> (value: cstr[128]);
rpc copy_test(data: bytes[128]) -> (ret_data: int);

rpc ping(a: uint8, b: int, c: bytes[77], d: uint) -> (a: uint8, b: int, c: bytes[77], d: uint);

rpc spawn_task(name: cstr[32]) -> (task: task);

oneway error(error: int);

/// The kernel sends this message to a pager task when an exception occurs.
oneway exception(task: task, reason: int);

/// The kernel calls this RPC when a page fault occurs.
/// When the pager task replies, the kernel continues executing the page-faulted task.
rpc page_fault(task: task, uaddr: uaddr, ip: uaddr, fault: uint) -> ();
