[id(1)]
interface kernel {
    type pid = isize
    type tid = isize
    type cid = isize

    [id(2), type(rpc)]
    create_process() -> (pid: pid, pager: cid)

    [id(3), type(rpc)]
    spawn_thread(pid: pid, start: usize) -> (tid: tid)

    [id(4), type(rpc)]
    add_pager(pid: pid, addr: usize, len: usize, flags: u8) -> ()
}
