[id(10)]
interface memmgr {
    type pid = isize

    // Used for benchmarking.
    [id(1), type(rpc)]
    nop() -> ()

    // Creates a process from an executable file in the initfs. The thread (`tid`)
    // is blocked until you start it by `exec_process`.
    [id(2), type(rpc)]
    create_process_from_initfs(path: string) -> (pid: pid)

    [id(3), type(rpc)]
    start_process(pid: pid) -> ()
}
