#!/bin/bash
set -ue

#
#  Setup the build environment
#
case "$(uname)" in
Darwin)
    ;;
Linux)
    VIRTUAL_ENV_DISABLE_PROMPT=true source venv/bin/activate
    ;;
*)
    echo "unsupported OS"
    exit 1
esac

#
#  Build Resea.
#
make BUILD=release V=1 --debug
