#!/bin/bash
set -ue

common_setup() {
    rustup component add rust-src

    if ! xargo --version > /dev/null 2>&1; then
        cargo install xargo
    fi

    pip3 install -r tools/requirements.txt
}

darwin_main() {
    common_setup
}

ubuntu_main() {
    virtualenv -p python3.7 venv
    VIRTUAL_ENV_DISABLE_PROMPT=true source venv/bin/activate

    common_setup
}

main() {
    case "$(uname)" in
    Darwin)
        darwin_main
        ;;
    Linux)
        ubuntu_main
        ;;
    *)
        echo "unsupported OS"
        exit 1
    esac
}

main