#!/bin/sh
set -ue
VERSION=3.1.0-rc0

if [ -f qemu/x86_64-softmmu/qemu-system-x86_64 ]; then
    echo "QEMU is already installed in $PWD/qemu, skipping..."
else
    rm -rf qemu
    wget https://download.qemu.org/qemu-$VERSION.tar.xz
    tar xf qemu-$VERSION.tar.xz
    mv qemu-$VERSION qemu
    cd qemu
    ./configure --target-list=x86_64-softmmu
    make -j2
fi
