#!/bin/bash
set -ue

progress() {
    echo -e "\033[1;32m==> \033[39m$*\033[0m"
}

run() {
    echo -e "\033[1m$*\033[0m"
    $*
}

common_setup() {
    progress "Setting up Rust toolchain"
    source $HOME/.cargo/env
    run rustup override set nightly
    run rustup component add rust-src

    if ! xargo --version > /dev/null 2>&1; then
        progress "Install xargo"
        run cargo install xargo
    fi

    progress "Install Python packages"
    run pip3 install --user -r tools/requirements.txt
}

darwin_main() {
    progress "Install Homebrew packages"
    run brew install llvm python3 binutils qemu bochs
    run brew install ./tools/homebrew/grub.rb

    if ! rustup --version > /dev/null 2>&1; then
        progress "Install rustup"
        run brew install rustup-init
        run rustup-init
    fi

    common_setup
}

ubuntu_main() {
    progress "Install apt packages"
    run sudo apt install -y lld-6.0 clang python3 python3-pip binutils \
        qemu-system-x86 grub-pc xorriso curl

    if ! rustup --version > /dev/null 2>&1; then
        progress "Install rustup"
        run curl https://sh.rustup.rs -sSf | sh
    fi

    common_setup
}

main() {
    # Move into the root of the repository.
    cd "$(git rev-parse --show-toplevel)"

    case "$(uname)" in
    Darwin)
        darwin_main
        ;;
    Linux)
        source /etc/lsb-release
        case "$DISTRIB_ID" in
        Ubuntu)
            ubuntu_main
            ;;
        *)
            echo "unsupported distribution"
            exit 1
        esac
        ;;
    *)
        echo "unsupported OS"
        exit 1
    esac
}

main
progress "Successfully installed prerequisites! Have fun!"